### ISSUE TITLE
How can change language zendesk form

### ISSUE THREAD

**Issue by v4n8877** [B3nnyL/react-zendesk#11]
Hi b3nnyl,

How can i set language zendesk form with language from my web.
I don't know what can i do this:
**import { ZendeskAPI } from "react-zendesk";
...
// Set Zendesk widgets in German
ZendeskAPI("webWidget", "setLocale", "de");**

Thanks!

**Comment by v4n8877** [comment]
Hi b3nnyl,

I did it, but i have new issue.
a language form does not change after change language a page.
So can you tell me fix this.

Thanks

**Comment by B3nnyL** [comment]
@v4n8877 thanks for sending the ticket. Currently react-zendesk only allows you to set locale for widget. 

For multi-language support of a contact form, please check: https://support.zendesk.com/hc/en-us/articles/203661456-Using-dynamic-content-to-translate-your-ticket-fields-Professional-and-Enterprise-

**Comment by BartusZak** [comment]
@v4n8877 how did u manage to change form language?

**Comment by BartusZak** [comment]
```js
<Zendesk defer onLoaded={() => ZendeskAPI("webWidget", "setLocale", "en")} zendeskKey={zendeskKey} />;
```
