### ISSUE TITLE
Failed prop type: Zendesk: prop type `defer` is invalid

### ISSUE THREAD

**Issue by IShinkarenko** [B3nnyL/react-zendesk#22]
Hi!
I got an error when installed react-zendesk in Next.js app:
` Failed prop type: Zendesk: prop type defer is invalid; it must be a function, usually from the prop-types package, but received undefined.This often happens because of typos such as PropTypes.function instead of PropTypes.func.`

"react": "^17.0.1"
"next": "^10.0.9"
"react-zendesk": "^0.1.11"

Thank you!

**Comment by IShinkarenko** [comment]
Hi @B3nnyL!
Could you please take a look on this small issue?
Thanks in advance!

**Comment by ericlundin** [comment]
See https://github.com/B3nnyL/react-zendesk/pull/24

**Comment by B3nnyL** [comment]
Fixed with #24. Cheers!
