### ISSUE TITLE
Incorrectly using PropTypes (boolean instead of bool)

### ISSUE THREAD

**Issue by bilo-io** [B3nnyL/react-zendesk#31]
@B3nnyL  Please see here:
Your code is producing a PropTypes warning, because `PropTypes.boolean` doesn't actually exist.

Please see [official React docs](https://reactjs.org/docs/typechecking-with-proptypes.html), it should be `PropTypes.bool`
![image](https://user-images.githubusercontent.com/3089012/123053497-3d663c00-d404-11eb-8e1b-36a960da9596.png)

Your code:
https://github.com/B3nnyL/react-zendesk/blob/6ce49f5131a6d7717e14865ea47ca2251bdb48c9/src/index.js#L69

![image](https://user-images.githubusercontent.com/3089012/122767384-e563f400-d2a2-11eb-9772-5f91f05cd21c.png)

**Comment by BartusZak** [comment]
See https://github.com/B3nnyL/react-zendesk/pull/24

**Comment by B3nnyL** [comment]
Fixed with #24. Cheers!
